# Generated by Django 6.0.2 on 2026-02-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_smtp_imap_to_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=50)),
                ('business_hours', models.JSONField(default=dict, help_text='Per-day timeframes: {"mon": [["09:00","17:00"]], ...}')),
                ('holidays', models.JSONField(default=dict, help_text='Date->name map: {"2026-12-25": "Weihnachten"}')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_calendar', to='core.organization')),
            ],
            options={
                'db_table': 'flux_business_calendars',
            },
        ),
    ]
