# Generated by Django 6.0.2 on 2026-02-07 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tickets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', '-created_at'], name='idx_ticket_org'),
        ),
    ]
