# Generated by Django 6.0.2 on 2026-02-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message_id',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='comment',
            name='message_id_md5',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
