# Generated by Django 6.0.2 on 2026-02-08 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businesscalendar'),
        ('tickets', '0005_add_message_id_to_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_agent_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_customer_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='next_response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_remaining_first_response',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_remaining_next_response',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_remaining_resolution',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0, help_text='Lower position = higher priority for matching.')),
                ('is_active', models.BooleanField(default=True)),
                ('priority_filter', models.JSONField(default=list, help_text='List of priority ints this SLA applies to, e.g. [3, 4].')),
                ('first_response_minutes', models.PositiveIntegerField(blank=True, help_text='Max business minutes for first agent response.', null=True)),
                ('next_response_minutes', models.PositiveIntegerField(blank=True, help_text='Max business minutes for agent reply after customer msg.', null=True)),
                ('resolution_minutes', models.PositiveIntegerField(blank=True, help_text='Max business minutes from creation to resolution.', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='core.organization')),
            ],
            options={
                'db_table': 'flux_slas',
                'ordering': ['organization', 'position'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.sla'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('escalation_at__isnull', False)), fields=['escalation_at'], name='idx_ticket_escalation_at'),
        ),
        migrations.AddConstraint(
            model_name='sla',
            constraint=models.UniqueConstraint(fields=('organization', 'position'), name='uq_sla_org_position'),
        ),
    ]
